# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_auto_20180225_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='locations',
        ),
        migrations.AddField(
            model_name='trip',
            name='locations',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='travelbuddy.Location'),
            preserve_default=False,
        ),
    ]
