# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0003_auto_20180225_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='locations',
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='locale_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='travelbuddy.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='travelers', to='travelbuddy.User'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
